name: CD
on:
  workflow_dispatch:
  
jobs:
  Pre-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Check if you are executing from a branch and exit if so ## MUST EXECUTE FROM TAG ##
      - name: Get branch or tag name
        id: get_ref_name
        run: echo "REF_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/')" >> $GITHUB_ENV

      - name: Check if it's a tag
        run: |
          if [[ -z "${REF_NAME}" ]]; then
            echo "This is not a tag. Exiting..."
            exit 1
          fi

  Deploy:
    needs: Pre-Check
    runs-on: ubuntu-latest
    env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      # Rebuild App
      - name: Set up NodeJS environment
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install package dependencies
        run: npm install
      
      - name: Build app
        run: npm run build


      # Apply Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_app_name: ${{ github.event.repository.name }}
          TF_VAR_version: ${{ github.ref }}
          TF_VAR_source_path: ${{ vars.SOURCE_PATH }}
          TF_VAR_cloudfront_origin_path: ${{ vars.CLOUDFRONT_ORIGIN_PATH }}
          TF_VAR_default_root_object: ${{ vars.DEFAULT_ROOT_OBJECT }}